# Generated by Django 2.2.13 on 2020-08-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dealcategory',
            field=models.CharField(choices=[('n', 'New'), ('u', 'Upgrade'), ('d', 'Downgrade')], default='n', max_length=1),
            preserve_default=False,
        ),
    ]
