# Generated by Django 2.2.13 on 2020-08-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_order_dealcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dealcategory',
            field=models.CharField(choices=[('n', 'New'), ('u', 'Upgrade'), ('d', 'Downgrade')], max_length=1, verbose_name='Deal Category'),
        ),
    ]
