# Generated by Django 2.2.13 on 2020-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Job Title'),
        ),
    ]
